name: proj2_real
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  cached_network_image: ^3.3.1
  cloud_firestore: ^4.17.0
  date_format: ^2.0.7
  firebase_auth: ^4.19.2
  firebase_core: ^2.30.0
  firebase_messaging: ^14.8.2
  firebase_storage: ^11.7.4
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.0
  image_picker: ^1.1.0
  intl: ^0.19.0
  photo_manager: ^3.0.0
  uuid: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - images/
